version: "3.7"

services:
  projects-service:
    image: michaelkoconnor/jumpstart-projects-service
    container_name: projects-service
    build:
      context: ./jumpstart-projects
      args:
        BUILD_ENV: development
    depends_on:
      - db-projects
    ports:
      - 3000:3000
    env_file: ./jumpstart-projects/.env

  comments-service:
    image: michaelkoconnor/jumpstart-comments-service
    container_name: comments-service
    build:
      context: ./jumpstart-comments
      args:
        BUILD_ENV: development
    depends_on:
      - db-projects
    ports:
      - 3001:3001
    env_file: ./jumpstart-comments/.env

  frontend:
    image: michaelkoconnor/jumpstart-frontend
    container_name: frontend
    build:
      context: ./jumpstart-frontend
      dockerfile: Dockerfile-dev
      args:
        BUILD_ENV: development
    ports:
      - 8080:8080
    volumes:
      - ./jumpstart-frontend/src/:/srv/src/

  reverse-proxy:
    image: michaelkoconnor/jumpstart-reverse-proxy
    container_name: reverse-proxy
    build: ./jumpstart-reverse-proxy
    depends_on:
      - projects-service
      - comments-service
      - frontend
    ports:
      - 80:80
      - 443:443

  lets-encrypt:
    image: linuxserver/letsencrypt
    container_name: lets-encrypt
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./letsencrypt:/config
    depends_on:
      - projects-service
      - comments-service
      - frontend
    environment:
      - PUID=1000
      - PGID=1000
      - URL=ec2-18-234-245-254.compute-1.amazonaws.com
      - SUBDOMAINS=www
      - TZ=America/Chicago
      - VALIDATION=http

  db-projects:
    image: postgres
    container_name: db-projects
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: jumpstartprojects
      POSTGRES_HOST: postgres
    volumes:
      - ./db-projects:/var/lib/postgresql/data

  seed-db:
    image: michaelkoconnor/jumpstart-projects-service
    container_name: seed-db
    build: ./jumpstart-projects
    command: npm run knex-remake
    depends_on:
      - db-projects
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    env_file: ./jumpstart-projects/.env
